on:
   workflow_run:
     workflows: ["Package testing"]
     types: [completed] #requested

env:
  BLYNK_TOKEN: DsyhOVtTuIcgdHfXdt5fV9yDt2P6XpAq

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v2=0"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v3=255"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v4=0"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v15=128"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: 
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v2=255"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v3=0"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v4=0"
          curl "https://blynk.cloud/external/api/update?token=$BLYNK_TOKEN&v15=128"
